$ANSIBLE_VAULT;1.1;AES256
61383837636163303737623762393365326565616234333437666331353936613632346564633139
6338646635613736333033383564343762363332343034630a343131656131656437376664333261
35323864643738393838303738326164623561373666323738353833326432356366666333313231
3731636562343764370a323064653435383430646433353835356363646437303631303332343865
38626164646631633537636337353738616232316132316662363938643835356239333536636364
65656334313361313162393734643437633664643562376266373131343038616432636136316265
35353937326136326533363561663963653261336431616537343636643935323762353037633937
35636232376165333338626333623833353564616437663263643139646131386161343035636362
62366164646135623031646337383664343730373661633637623161316531616662
