---
- name: tunnel user
  ansible.builtin.user:
    name: tunnel
    create_home: true
    state: present
    shell: /usr/sbin/nologin

- name: tunnel ssh keys
  ansible.posix.authorized_key:
    user: tunnel
    state: present
    key: "{{ item }}"
  loop: "{{ tunnel_ssh_keys }}"

- name: configure sshd for tunneling
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PubkeyAuthentication", value: "yes" }
    - { key: "ClientAliveInterval", value: "30" }
    - { key: "ClientAliveCountMax", value: "2" }
    - { key: "GatewayPorts", value: "clientspecified" }
  notify: sshd-restart
