---
- name: tunnel user
  ansible.builtin.user:
    name: tunnel
    create_home: true
    state: present
    shell: /usr/sbin/nologin

- name: tunnel ssh keys
  ansible.posix.authorized_key:
    user: tunnel
    state: present
    key: "{{ item }}"
  loop: "{{ tunnel_ssh_keys }}"

- name: configure sshd for tunneling
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PubkeyAuthentication", value: "yes" }
    - { key: "ClientAliveInterval", value: "30" }
    - { key: "ClientAliveCountMax", value: "2" }
    - { key: "GatewayPorts", value: "clientspecified" }
  notify: sshd-restart

- name: install nginx and certbot
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
      - python3-certbot
      - python3-certbot-nginx
    state: present
  notify: nginx-start
  tags:
    - certbot-setup

- name: main nginx conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: nginx-reload
  tags:
    - certbot-setup

- name: register certbot
  shell: |
    certbot -n register --agree-tos --email tonyebel123@gmail.com
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered
  tags:
    - certbot-setup

- name: nginx sites-available
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: nginx-reload
  loop: "{{ nginx_sites }}"

- name: nginx sites-enabled
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  notify: nginx-reload
  loop: "{{ nginx_sites }}"

- name: certbot systemd service
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - certbot.service
    - certbot.timer
  notify: certbot-timer-restart
  tags:
    - certbot-setup

- name: enable certbot.timer
  ansible.builtin.systemd_service:
    name: certbot.timer
    state: started
    enabled: true
  tags:
    - certbot-setup

- name: certbot get certificates
  command: "/usr/bin/certbot -n --nginx certonly -d {{ item }}"
  args:
    creates: "/etc/letsencrypt/live/{{ item }}"
  loop: "{{ nginx_sites }}"
  tags:
    - certbot-setup

- name: tonyebel-portfolio repo
  ansible.builtin.git:
    repo: "git@github.com:tony-ebel/tonyebel-portfolio.git"
    dest: /opt/tonyebel-portfolio
    version: main
    clone: true
    update: true
    accept_hostkey: true
  notify: portfolio-restart

- name: portfolio systemd service
  ansible.builtin.copy:
    src: portfolio.service
    dest: /etc/systemd/system/portfolio.service
    mode: "0644"
  notify: portfolio-restart
