---
- name: tunnel user
  ansible.builtin.user:
    name: tunnel
    create_home: true
    state: present
    shell: /usr/sbin/nologin

- name: tunnel ssh keys
  ansible.posix.authorized_key:
    user: tunnel
    state: present
    key: "{{ item }}"
  loop: "{{ tunnel_ssh_keys }}"

- name: configure sshd for tunneling
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PubkeyAuthentication", value: "yes" }
    - { key: "ClientAliveInterval", value: "30" }
    - { key: "ClientAliveCountMax", value: "2" }
    - { key: "GatewayPorts", value: "clientspecified" }
  notify: sshd-restart

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  notify: nginx-start

- name: main nginx conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: nginx-reload

- name: nginx sites-available
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: nginx-reload
  loop: "{{ nginx_sites }}"

- name: nginx sites-enabled
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  notify: nginx-reload
  loop: "{{ nginx_sites }}"

- name: nginx verify config
  ansible.builtin.command: nginx -t
  changed_when: false
  failed_when: "'test failed' in nginx_test_output.stderr"
  register: nginx_test_output
