$ANSIBLE_VAULT;1.1;AES256
34653232343161623838613365656336326264666636323562383335326230643265326431616238
3365336463336336313438623538383432653564633436640a356537386333396438656264303631
30326165326665643636303636316264353331313538383762643164343638363030386166626432
6634616537376531330a366337623962343335336662323464643630616534373764643138333266
63386461393966386233383031333361393765326532343335313339376666656235303138663861
30313337636661383962656236343137333238313066386561613734323839376132313361373830
39623235353231623161383235306138653233666438313661646363343163343038616365353838
32656632363061653063383230313139323630653935666663653937333136353061373830656533
3830
