$ANSIBLE_VAULT;1.1;AES256
62653832356666353939393436343066633635373535613762386338643832396430396530353336
6164373239663237323231663636376631306265643137660a316436636535313663323930346530
33663362653862306435613565376234623735336138313739613262343966636665353433303761
3563656538373235360a363862353863336631393232623134386139623638613133636534383430
39646136333936346337383363373830383361383933643264373761353636306336376165333265
36333233613861383466646330333265353330353665373661376131663061393661613636383030
61653534623765386338313361633537316535356135383463356537303265653939633239653134
39303963323031623466363936393336366565343037663235383638643266373961643366306538
30663265646263383266663530636261336265386237373965666231346465303539
