$ANSIBLE_VAULT;1.1;AES256
61626162643962363762343330396264363866376336386361363536326231346334323236306637
6237343861646265656233623366613332663361333538340a616535383634393334336266306265
63356437353863386465316430333536363661376563383236363063353938303532663732326530
3631316333613237620a613463333232306565666565646562666566363834333330383837323731
38333464356562646633373665653237323365646139653233633065393436636331386338383864
30636233316262633435386665376464396463316530393430346438396233656436363264613432
36333564316237636531383433656434383533313261323139353038616231363265636533303837
62313337356234326261373764303932333566393339393063326531323464383333623638316330
3230
