---
- name: Set custom arch variable
  set_fact:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add docker gpg key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Setup stable docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure docker service is started and enabled
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Add tony to docker group
  ansible.builtin.user:
    name: tony
    groups: docker
    append: true

- name: Setup clean-docker services
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - clean-docker.service
    - clean-docker.timer
  notify: clean-docker-restart
